name: mobile
description: "SkillMart AI Mobile App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:

    sdk: flutter
  http: ^1.2.1
  file_picker: ^8.0.3
  http_parser: ^4.0.2
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.10
  flutter_animate: ^4.5.0
  url_launcher: ^6.2.5
  shared_preferences: ^2.5.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/backgrounded logo.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/logo.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/backgrounded logo.png
    - assets/background.webp